# This is a workflow that can be run manually to build & test
name: Build & Test 🚀

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: macos-11

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Setup 🛠
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically

      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_12.5.1.app/Contents/Developer'

      - name: Xcode Build & Test ✅
        run: xcodebuild -project Intercom-Invites.xcodeproj -scheme Intercom-Invites -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=14.3" test
